### ISSUE TITLE
error threw if use my own map

### ISSUE THREAD

**Issue by hzcipher** [mit-racecar/particle_filter#1]
process[map_server-1]: started with pid [18093]
process[Particle_filter-2]: started with pid [18094]
('getting map from service: ', 'static_map')
Traceback (most recent call last):
  File "/home/botkit/catkin_ws2/src/botkit/localization/particle_filter/src/particle_filter.py", line 679, in <module>
    pf = ParticleFiler()
  File "/home/botkit/catkin_ws2/src/botkit/localization/particle_filter/src/particle_filter.py", line 103, in __init__
    self.get_omap()
  File "/home/botkit/catkin_ws2/src/botkit/localization/particle_filter/src/particle_filter.py", line 139, in get_omap
    oMap = range_libc.PyOMap(map_msg)
  File "/RangeLibc.pyx", line 156, in range_libc.PyOMap.__cinit__ (RangeLibc.cpp:3060)
IndexError: index 832 is out of bounds for axis 1 with size 832

**Comment by kctess5** [comment]
This is a known bug, it happens when you use a map which is not square. We will fix this very soon!

In the mean time, you should make the width and height dimensions of your map image equal, and it should work.

Thanks!

**Comment by kctess5** [comment]
I just fixed the bug. It was actually an issue with RangeLibc, not the particle filter. To fix, just run "git pull" in your RangeLibc directory, and then re-run the compile script inside the "pywrapper" directory.

https://github.com/kctess5/range_libc/commit/bc3b268e004e25a554a6bfc7a671f07bf5ef8bc7
